import type { Metadata } from "next";
import "./globals.css";
import { DestinationProvider } from "@/context/destinationContext";

export const metadata: Metadata = {
  title: "Space tourism",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <DestinationProvider>
          {children}
        </DestinationProvider>
      </body>
    </html>
  );
}
